@extends('admin.layouts.master')
@section('content')
<div class="source-page-content">
    <nav class="page-breadcrumb">
        <a href="{{ route('admin.dashboard') }}">Dashboard</a>
        <i class="bi bi-chevron-right"></i>
        <a href="{{ route('admin.bookings') }}">Bookings</a>
        <i class="bi bi-chevron-right"></i>
        <span>Source Summary</span>
    </nav>
    <section class="page-heading source-page-heading">
        <div>
            <p>Booking Analytics</p>
            <h1>Source Summary</h1>
            <span>
                Compare bookings and revenue generated by every sales channel.
            </span>
        </div>
        <button
            type="button"
            class="export-source-button"
            id="exportSources"
        >
            <i class="bi bi-download"></i>
            Export Report
        </button>
    </section>
    <section class="source-summary-grid">
        <article>
            <span class="summary-icon blue">
                <i class="bi bi-diagram-3"></i>
            </span>
            <div>
                <p>Total Sources</p>
                <h2>
                    {{ $totalSources }}
                </h2>
                <small>
                    Active booking channels
                </small>
            </div>
        </article>
        <article>
            <span class="summary-icon purple">
                <i class="bi bi-journal-check"></i>
            </span>
            <div>
                <p>Total Bookings</p>
                <h2>
                    {{ number_format($totalBookings) }}
                </h2>
                <small>
                    {{ number_format($totalConfirmed) }} confirmed
                </small>
            </div>
        </article>
        <article>
            <span class="summary-icon green">
                <i class="bi bi-cash-stack"></i>
            </span>
            <div>
                <p>Total Revenue</p>
                <h2>
                    THB {{ number_format($totalAmount, 2) }}
                </h2>
                <small>
                    Selected period revenue
                </small>
            </div>
        </article>
        <article>
            <span class="summary-icon orange">
                <i class="bi bi-graph-up-arrow"></i>
            </span>
            <div>
                <p>Average Booking Value</p>
                <h2>
                    THB {{ number_format($averageValue, 2) }}
                </h2>
                <small>
                    {{ number_format($totalCancelled) }} cancelled bookings
                </small>
            </div>
        </article>
    </section>
    <section class="content-card source-card">
        <div class="source-filter-bar">
            <div class="filter-field">
                <label for="sourceFromDate">
                    From Date
                </label>
                <input
                    type="date"
                    class="form-control"
                    id="sourceFromDate"
                    value="{{ request('from_date') }}"
                >
            </div>
            <div class="filter-field">
                <label for="sourceToDate">
                    To Date
                </label>
                <input
                    type="date"
                    class="form-control"
                    id="sourceToDate"
                    value="{{ request('to_date') }}"
                >
            </div>
            <div class="filter-field source-type-field">
                <label for="sourceType">
                    Source Type
                </label>
                <select
                    class="form-select"
                    id="sourceType"
                >
                    <option
                        value="all"
                        {{ request('source_type', 'all') == 'all' ? 'selected' : '' }}
                    >
                        All Source Types
                    </option>
                    @foreach($sourceTypes as $type)
                        <option
                            value="{{ strtolower($type) }}"
                            {{ request('source_type') == strtolower($type) ? 'selected' : '' }}
                        >
                            {{ $type }}
                        </option>
                    @endforeach
                </select>
            </div>
            <!-- <button
                type="button"
                class="apply-source-filter"
                id="applySourceFilter"
            >
                <i class="bi bi-funnel"></i>
                Apply Filter
            </button> -->
            <button
                type="button"
                class="reset-source-filter"
                id="resetSourceFilter"
            >
                <i class="bi bi-arrow-counterclockwise"></i>
                Reset
            </button>
        </div>
        <div class="source-table-toolbar">
            <!-- <div class="source-search">
                <i class="bi bi-search"></i>
                <input
                    type="search"
                    id="sourceSearch"
                    value="{{ request('search') }}"
                    placeholder="Search source name..."
                >
            </div> -->
            <!-- <div class="table-meta">
                <span>
                    <i class="bi bi-calendar3"></i>
                    @if(request('from_date') && request('to_date'))
                        {{ date('d M Y', strtotime(request('from_date'))) }}
                        –
                        {{ date('d M Y', strtotime(request('to_date'))) }}
                    @else
                        All Dates
                    @endif
                </span>
               <label>
                    Show
                    <select id="sourcePageLength">
                        <option value="20">20</option>
                    </select>
                    entries
                </label>
            </div>-->
        </div>
        <div class="table-responsive">
            <table
                class="table source-table align-middle mb-0"
                id="sourceTable"
            >
                <thead>
                    <tr>
                      <th class="source-sort" data-sort="name">
                            Source Name
                            <i class="bi bi-chevron-down"></i>
                        </th>

                        <th class="source-sort" data-sort="type">
                            Source Type
                            <i class="bi bi-chevron-down"></i>
                        </th>

                        <th class="source-sort" data-sort="bookings">
                            Total Bookings
                            <i class="bi bi-chevron-down"></i>
                        </th>

                        <th class="source-sort" data-sort="amount">
                            Performance
                            <i class="bi bi-chevron-down"></i>
                        </th>

                        <th class="source-sort" data-sort="confirmed">
                            Confirmed
                            <i class="bi bi-chevron-down"></i>
                        </th>

                        <th class="source-sort" data-sort="cancelled">
                            Cancelled
                            <i class="bi bi-chevron-down"></i>
                        </th>

                        <th class="source-sort" data-sort="amount">
                            Total Amount (THB)
                            <i class="bi bi-chevron-down"></i>
                        </th>

                        <th class="source-sort" data-sort="last_booking">
                            Last Booking
                            <i class="bi bi-chevron-down"></i>
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($sources as $index => $source)
                        @php
                            $percentage = $maxAmount
                                ? ($source['amount'] / $maxAmount) * 100
                                : 0;
                            $initials = strtoupper(
                                substr(
                                    preg_replace(
                                        '/[^A-Za-z]/',
                                        '',
                                        $source['name']
                                    ),
                                    0,
                                    2
                                )
                            );
                        @endphp
                        <tr
                            data-source-type="{{ strtolower($source['type']) }}"
                            data-date="{{ $source['last_booking'] ?? '' }}"
                            data-bookings="{{ (int) $source['bookings'] }}"
                            data-amount="{{ number_format($source['amount'], 2, '.', '') }}"
                        >
                            <td>
                                <div class="source-name">
                                    <span>
                                        {{ $initials }}
                                    </span>
                                    <div>
                                        <strong>
                                            {{ $source['name'] }}
                                        </strong>
                                        <small>
                                            Source ID:
                                            SRC-{{
                                                str_pad(
                                                    $index + 101,
                                                    4,
                                                    '0',
                                                    STR_PAD_LEFT
                                                )
                                            }}
                                        </small>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <span
                                    class="source-type {{ strtolower($source['type']) }}"
                                >
                                    {{ $source['type'] }}
                                </span>
                            </td>
                            <td>
                                <strong class="booking-count">
                                    {{ number_format($source['bookings']) }}
                                </strong>
                                <small>
                                    {{
                                        $totalBookings
                                            ? number_format(
                                                ($source['bookings'] / $totalBookings) * 100,
                                                1
                                            )
                                            : 0
                                    }}% of total
                                </small>
                            </td>
                            <td>
                                <div class="performance-bar">
                                    <span
                                        style="width: {{ number_format($percentage, 1, '.', '') }}%"
                                    ></span>
                                </div>
                                <small>
                                    {{ number_format($percentage, 1) }}%
                                    revenue share
                                </small>
                            </td>
                            <td>
                                <span class="count-pill confirmed">
                                    <i></i>
                                    {{ number_format($source['confirmed']) }}
                                </span>
                            </td>
                            <td>
                                <span class="count-pill cancelled">
                                    <i></i>
                                    {{ number_format($source['cancelled']) }}
                                </span>
                            </td>
                            <td>
                                <strong class="source-amount">
                                    THB
                                    {{ number_format($source['amount'], 2) }}
                                </strong>
                            </td>
                            <td>
                                <strong>
                                    @if(!empty($source['last_booking']))
                                        {{
                                            date(
                                                'd M Y',
                                                strtotime($source['last_booking'])
                                            )
                                        }}
                                    @else

                                        N/A
                                    @endif
                                </strong>
                            </td>
                            <td>
                                <a
                                    href="{{ route('admin.source.booking.details', [
                                        'source' => $source['name'],
                                        'from' => request('from_date'),
                                        'to' => request('to_date')
                                    ]) }}"
                                    class="view-source-button"
                                    title="View source bookings"
                                >
                                    <i class="bi bi-eye"></i>
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td
                                colspan="9"
                                class="text-center py-4"
                            >
                                No source data found.
                            </td>

                        </tr>
                    @endforelse
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">
                            <strong>
                                Visible Source Total
                            </strong>
                            <small id="visibleSourceCount">
                                {{ $sources->count() }}

                                {{
                                    $sources->count() == 1
                                        ? 'source'
                                        : 'sources'
                                }}
                            </small>
                        </td>
                        <td>
                            <strong id="visibleSourceBookings">
                                {{ number_format($totalBookings) }}
                            </strong>
                        </td>
                        <td></td>
                        <td>
                            <strong>
                                {{ number_format($totalConfirmed) }}
                            </strong>
                        </td>
                        <td>
                            <strong>
                                {{ number_format($totalCancelled) }}
                            </strong>
                        </td>
                        <td>
                            <strong
                                class="source-grand-total"
                                id="visibleSourceAmount"
                            >
                                THB
                                {{ number_format($totalAmount, 2) }}
                            </strong>
                        </td>
                        <td colspan="2"></td>
                    </tr>
                </tfoot>
            </table>
        </div>
</section>
<style>
.source-card .dataTables_wrapper {
    width: 100%;
    padding: 0 18px;
    box-sizing: border-box;
}
.source-card .dataTables_wrapper .dataTables_length,
.source-card .dataTables_wrapper .dataTables_filter {
    padding: 15px 0;
    margin: 0;
    font-size: 9px;
    color: #8994a4;
}
.source-card .dataTables_wrapper .dataTables_length {
    float: left;
}
.source-card .dataTables_wrapper .dataTables_filter {
    float: right;
}
.source-card .dataTables_wrapper .dataTables_length select {
    height: 36px;
    min-width: 70px;
    margin: 0 6px;
    padding: 0 25px 0 10px;
    border: 1px solid #e4eaf1;
    border-radius: 7px;
    background: #fff;
    font-size: 9px;
    color: #344054;
}
.source-card .dataTables_wrapper .dataTables_filter input {
    width: 260px;
    height: 38px;
    margin-left: 8px;
    padding: 0 12px;
    border: 1px solid #e4eaf1;
    border-radius: 8px;
    background: #fff;
    font-size: 9px;
}
.source-card .dataTables_wrapper .dataTables_paginate {
    float: right;
    padding: 10px 0 15px;
}
.source-card .dataTables_wrapper .dataTables_paginate .paginate_button {
    display: inline-flex !important;
    align-items: center;
    justify-content: center;
    min-width: 32px;
    height: 32px;
    margin: 0 2px !important;
    padding: 0 9px !important;
    border: 1px solid #e4eaf1 !important;
    border-radius: 6px !important;
    background: #fff !important;
    color: #344054 !important;
    font-size: 9px;
}
.source-card .dataTables_wrapper .dataTables_paginate .paginate_button.current {
    border-color: var(--slw-primary) !important;
    background: var(--slw-primary) !important;
    color: #fff !important;
}
.source-card .dataTables_wrapper .dataTables_info {
    float: left;
    padding: 14px 0 !important;
    margin: 0 !important;
    font-size: 12px !important;
    font-weight: 500;
    color: #8994a4 !important;
    line-height: 32px;
}
.source-card .dataTables_wrapper .dataTables_info strong {
    color: #172033;
    font-weight: 700;
}
.source-card .dataTables_wrapper .dataTables_paginate {
    float: right;
    padding: 10px 0 14px !important;
    margin: 0 !important;
}
.source-card .dataTables_wrapper .dataTables_paginate .paginate_button {
    min-width: 34px !important;
    height: 34px !important;
    margin: 0 3px !important;
    padding: 0 !important;
    display: inline-flex !important;
    align-items: center;
    justify-content: center;
    border: 1px solid #e4eaf1 !important;
    border-radius: 7px !important;
    background: #fff !important;
    color: #344054 !important;
    font-size: 12px !important;
    font-weight: 600;
    box-shadow: none !important;
}
.source-card .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
    background: #fff7f5 !important;
    border-color: #ffb2a4 !important;
    color: var(--slw-primary) !important;
}
.source-card .dataTables_wrapper .dataTables_paginate .paginate_button.current,
.source-card .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
    background: var(--slw-primary) !important;
    border-color: var(--slw-primary) !important;
    color: #fff !important;
}
.source-card .dataTables_wrapper .dataTables_paginate .paginate_button.disabled,
.source-card .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:hover {
    background: #f8f9fa !important;
    color: #a8b0bb !important;
    border-color: #e4eaf1 !important;
}
.source-card .dataTables_wrapper::after {
    content: "";
    display: table;
    clear: both;
}
@media (max-width: 700px) {
    .source-card .dataTables_wrapper .dataTables_info,
    .source-card .dataTables_wrapper .dataTables_paginate {
        float: none !important;
        text-align: left !important;
    }
    .source-card .dataTables_wrapper .dataTables_paginate {
        margin-top: 5px !important;
    }
}
</style>
@endsection