<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //Call db table
    protected $table = 'orders';

    //Fillable fields
    protected $fillable = [
        'item_id',
        'type',
        'start_date',
        'end_date',
        'qty_adult',
        'qty_child',
        'amount_adult',
        'amount_child',
        'total_amount',
        'paypal_transaction_id',
        'payment_data',
        'date',
        'userID',
        'userRole',
        'item_name',
        'first_name',
        'last_name',
        'email',
        'phone_country_code',
        'phone',
        'offers_receive',
        'terms_and_conditions',
        'from',
        'to',
        'assign_supplier',
        'meal_type',
        'meal_transfer_type',
        'meal_food_type',
        'pickup_time',
        'star_rating_adult',
        'star_rating_child',
        'HotelName',
        'HotelAddress',
        'HotelNameFrom',
        'HotelNameTo',
        'TransferPax',
        'TransferTime',
        'TransferFrom',
        'TransferFromAddress',
        'ContactPhone',
        'OtherDetails',
        'status',
        'refundable_amount',
        'cancel_reason',
        'currency',
        'timestamp',
        'supplier_name',
        'booking_reference',
        'remark',
        'source',
        'flight_no',
        'flight_time',
        'departure_flight_no',
        'departure_flight_time',
        'payment_status',
        'paid_payment_date',
        'flight_arrival',
        'flight_departure',
        'passport_no',
        'parent_booking_id',
        'itinerary_number',
        'sub_supplier_id',
        'ip_address',
        'kk_prod_no',
        'kk_pkg_no',
        'kk_item_no',
        'kk_order_no',
        'kk_order_oid',
        'kk_order_master_mid',
        'payment_mode',
        'markup',
        'ViatorBookingReference',
        'ViatorProduct_Option_Id',
        'payment_remark',
        'supplier_remark',
        'last_minute',
        'option_id',
        'manually_booking_made_by',
        'conversion_rate',
        'conversion_type',
        'fasttrack_amount',
        'fasttrack_currency',
    ];
}